name: Build Unity Project

on:
  push:
    branches: [ main ]

jobs:
  buildWindows:
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-

      - name: Setup Unity
        uses: game-ci/setup-unity@v3
        with:
          unityVersion: 2022.3.46f1

      - name: Activate License
        uses: game-ci/activate-license@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project
        uses: game-ci/build@v2
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build-Windows
          path: build/StandaloneWindows64
